version: '3'

services:
  pdf-chatbot:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./docs:/app/docs
      - ./config.json:/app/config.json
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

